# Generated by Django 3.0.3 on 2020-04-22 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classprice',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_price',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ClassPrice'),
        ),
    ]
