# Generated by Django 3.0.3 on 2020-04-22 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('skill_value', models.CharField(blank=True, max_length=100, null=True)),
                ('level_value', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
