# Generated by Django 3.0.3 on 2020-04-21 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_country'),
        ('users', '0002_auto_20200421_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.Country'),
        ),
    ]
