# Generated by Django 3.0.3 on 2020-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200422_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
